spring.application.name=sporttrack

# Configuration PostgreSQL
spring.datasource.url=jdbc:postgresql://86.206.137.95:5432/PROJET_POO_GP11
spring.datasource.username=PROJET_POO_GP11
spring.datasource.password=HYUKsq8Mnsnxcx3p2sYFecaPxZCAbFr4
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=false

# Port du serveur
server.port=8080

# Photos de profil (dossier sur disque ; par défaut sous src/main/resources/static pour le dev école)
sporttrack.profile-upload-path=${user.dir}/src/main/resources/static/uploads/profiles

spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha